name: Ubuntu Packaging

on:
  release:
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      env: 
        DEBIAN_FRONTEND: "noninteractive"
    - name: Prepare Environment
      run: |
        echo "deb http://repo.vitexsoftware.cz $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/vitexsoftware.list
        sudo wget -O /etc/apt/trusted.gpg.d/vitexsoftware.gpg http://repo.vitexsoftware.cz/keyring.gpg
        sudo apt-get update
        sudo apt-get install -y aptitude moreutils composer exim4 pbuilder ubuntu-dev-tools apt-file debhelper phpdocumentor
    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1
      with:
        source_directory: .
        artifacts_directory: dist
        
